package-lock.json, package.json, src/App.css, src/App.js
This fix #12
And remove a warning
=> Add colors to background color buttons

src/shadows.js
Hi, I've tried to add 3 new shadows to the file.
Solves issue #4
=> Added shadows

src/App.css, src/App.js, src/colors.js, src/components/ColorList/ColorList.js, src/components/PageFooter/PageFooter.js
=> Improve design for background switcher

src/App.css, src/shadows.js
Added On card hover Animation
Added AirBNB landin page card.
=> added hover Animation & Added AirBnb Card

src/App.css
Added flex properties to App.css to make card aligned to each other.
#25
=> Fixed cards alignment issue

package-lock.json, package.json, src/components/ColorList/ColorList.js
=> Show background switcher value on hover

README.md
i have added instruction, how to fork and clone the repository with the command and the how to PR.
please check !!
=>  update the readme file with instruction 

src/shadows.js
Just like in the screenshot below
=> Added Twitter tweet button

README.md
Added missing space on line 9, also included a note on line 66 on how to create a new branch and switch to it.
=> Fixed type error

src/shadows.js
=> Added Netflix login modal shadow

src/shadows.js
=> Added linkedIn HomePage searchbox Shadow

src/shadows.js
* Added Box-Shadows for Udemy courses cards
* related to #45
=> udemy-courses

src/shadows.js
Also fixed indentation and typo on line 134
=> Added Waze and BitBucket

src/shadows.js
=> Added Paytm div border style

src/shadows.js
This pull requests removes the generic inset shadows as requested in #51
=> Removed the inset shadows from shadows.js

package-lock.json, package.json, src/App.css, src/App.js, src/components/ColorList/ColorList.js, src/components/ColorPicker.js
Here we go mate, all done. Hope you like it
=> Dynamic color picker added to the footer

src/shadows.js
Update shadow.js with values for npm buttons
=> Add npm main button box shadow values

src/shadows.js
Add shadow box values for main window of Glitch website.
=> Glitch main window shadow

src/App.css
fixed colour box hiding last element in mobile view by adding margin-bottom and padding-bottom
=> color box fix

src/App.css
fixed blocking of last block by color bar in mobile view and added margin to left and right to fix the google bar being right up against the screen
=> fixed color-bar blocking the last block in mobile view by adding padding-bottom

src/shadows.js
Attached below is the screenshot of the feature cards of codementor.io
Please let me know if any changes to be done.
Reference: https://www.codementor.io/
Thank you for the opportunity.
=> Add new card featuring code mentor feature card's shadow & border design

src/shadows.js
=> Added Udacity Testimonial box shadow

src/shadows.js
Added a hover shadow I admired from Quicken Loans. 
This is for issue #4
=> Add box shadow from quicken loans style

src/shadows.js
Here I've added a Material Design Box shadow design from codepen
=> material design box shadow design added

src/App.js
Added sorting function by shadow name which fixes the issue #136
=> Sort shadows in alphabetical order

src/shadows.js
Updating box shadows for https://github.com/nakulrathore/Box-Shadows/issues/45
=> Updating box shadows

src/shadows.js
hey, there I just add 5 more cool shadows 👍
=> added Soft Neumorphism, Neon Pink, gradient shadow, classic lamp, upards gradient

src/shadows.js
Add Starbuck boxshadow
Issue #45
=> feat: add Starbucks boxshadow
